version: '3.8'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - NUMBA_THREADING_LAYER=tbb
    depends_on:
      - db

  db:
    image: "pgvector/pgvector:pg17"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data: