"""Adds book column

Revision ID: 0095adb66e16
Revises: 2c622f7581fd
Create Date: 2025-01-01 18:47:06.652681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0095adb66e16'
down_revision: Union[str, None] = '2c622f7581fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motivational_quotes', sa.Column('book', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motivational_quotes', 'book')
    # ### end Alembic commands ###
