"""Add pg_trgm extension

Revision ID: 834e70386392
Revises: 0095adb66e16
Create Date: 2025-01-02 14:06:06.271676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834e70386392'
down_revision: Union[str, None] = '0095adb66e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.execute('CREATE INDEX trgm_idx_book ON motivational_quotes USING gin (book gin_trgm_ops)')
    op.execute('CREATE INDEX trgm_idx_author ON motivational_quotes USING gin (author gin_trgm_ops)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('trgm_idx_author', table_name='motivational_quotes')
    op.drop_index('trgm_idx_book', table_name='motivational_quotes')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
    # ### end Alembic commands ###
