"""Makes author field optional

Revision ID: d37254748f4d
Revises: 05bb4a5930d9
Create Date: 2024-12-25 11:03:28.485911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37254748f4d'
down_revision: Union[str, None] = '05bb4a5930d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motivational_quotes', 'author', existing_type=sa.String(), nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motivational_quotes', 'author', existing_type=sa.String(), nullable=False)
    pass
    # ### end Alembic commands ###
