"""Renames quote fields

Revision ID: daf35cb9d29c
Revises: d37254748f4d
Create Date: 2024-12-25 16:54:29.745242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daf35cb9d29c'
down_revision: Union[str, None] = 'd37254748f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motivational_quotes', sa.Column('text', sa.String(), nullable=True))
    op.add_column('motivational_quotes', sa.Column('reduced_embeddings', sa.ARRAY(sa.Float()), nullable=True))
    op.drop_column('motivational_quotes', 'quote')
    op.drop_column('motivational_quotes', 'pca_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motivational_quotes', sa.Column('pca_embeddings', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.add_column('motivational_quotes', sa.Column('quote', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('motivational_quotes', 'reduced_embeddings')
    op.drop_column('motivational_quotes', 'text')
    # ### end Alembic commands ###
